# Generated by Django 4.1.13 on 2025-02-10 09:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("innovatex", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blogpost",
            options={
                "ordering": ["-created_at", "-updated_at"],
                "verbose_name": "BlogPost",
                "verbose_name_plural": "BlogPosts",
            },
        ),
        migrations.AlterModelOptions(
            name="casestudy",
            options={
                "ordering": ["-created_at", "-updated_at"],
                "verbose_name": "CaseStudy",
                "verbose_name_plural": "CaseStudies",
            },
        ),
        migrations.AlterModelOptions(
            name="client",
            options={
                "ordering": ["-created_at", "-updated_at"],
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
            },
        ),
        migrations.AlterModelOptions(
            name="contactmessage",
            options={
                "ordering": ["-created_at", "-updated_at"],
                "verbose_name": "ContactMessage",
                "verbose_name_plural": "ContactMessages",
            },
        ),
        migrations.AlterModelOptions(
            name="services",
            options={
                "ordering": ["-created_at", "-updated_at"],
                "verbose_name": "Services",
                "verbose_name_plural": "Service",
            },
        ),
        migrations.AlterModelOptions(
            name="teammember",
            options={
                "ordering": ["-created_at", "-updated_at"],
                "verbose_name": "TeamMember",
                "verbose_name_plural": "TeamMembers",
            },
        ),
        migrations.AlterModelOptions(
            name="testimonial",
            options={
                "ordering": ["-created_at", "-updated_at"],
                "verbose_name": "Testimonial",
                "verbose_name_plural": "Testimonials",
            },
        ),
    ]
